title: "My Portfolio"
description: "Showcasing my projects and tutorials."
remote_theme: mmistakes/minimal-mistakes

# Enable plugins
plugins:
  - jekyll-include-cache

# Navigation (Minimal Mistakes handles this differently)
header_pages:
  - index.md
  - projects.md
  - tutorials.md
  - contact.md

# Ensure skin loads
minimal_mistakes_skin: default

