title: "My Portfolio"
description: "Showcasing my projects and tutorials."
theme: jekyll-theme-modernist


plugins:
  - jekyll-include-cache

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Tutorials"
    url: "/tutorials"
  - title: "Contact"
    url: "/contact"
