title: "Your Name's Portfolio"
description: "Showcasing my bioinformatics research, coding projects, and tutorials."
theme: jekyll-theme-minimal  # You can change this theme later

# Navigation menu (Main Tabs)
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Tutorials"
    url: "/tutorials"
  - title: "Contact"
    url: "/contact"

show_downloads: false
