title: "My Portfolio"
description: "Showcasing my projects and tutorials."
remote_theme: "mmistakes/minimal-mistakes"  # or any valid theme

plugins:
  - jekyll-include-cache

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Tutorials"
    url: "/tutorials"
  - title: "Contact"
    url: "/contact"
